version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=count_of_money
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  api:
    build: "./api"
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/count_of_money
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: count_of_money
      JWT_SECRET: countofmoney
      MODE: DEV
      RUN_MIGRATIONS: "true"
    ports:
      - '3000:3000'
    expose:
      - 3000
    volumes:
      - ./api:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
  front:
    build: "./front"
    ports:
      - "3001:3000"
    expose:
      - 3000
    networks:
      - default
    restart: on-failure
    volumes:
      - ./front:/app

networks:
  default:
volumes:
  pgdata: