version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12
#    networks:
#      - webnet
#    env_file:
#      - ./api/.env
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "count_of_money"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  api:
    container_name: api
    env_file:
      - ./api/.env
    build:
      context: ./api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
#    networks:
#      - webnet
    depends_on:
      - postgres
  front:
    build: "./front"
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - default
    restart: on-failure
    volumes:
      - ./front:/app

networks:
  default:
volumes:
  pgdata: