version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12
#    networks:
#      - webnet
    env_file:
      - ./api/.env
    environment:
      POSTGRES_PASSWORD: $${POSTGRES_PASSWORD}
      POSTGRES_USER: $${POSTGRES_USER}
      POSTGRES_DB: $${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
#    networks:
#      - webnet
    depends_on:
      - postgres
  #  api:
#    build: "./api"
#    depends_on:
#      - db
#    environment:
#      MIX_ENV: dev
#    env_file:
#      - .env
#    ports:
#      - '3001:3000'
#    expose:
#      - 3000
#    volumes:
#      - ./api:/app
  front:
    build: "./front"
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - default
    restart: on-failure
    volumes:
      - ./front:/app

networks:
  default:
volumes:
  pgdata: